"""CLAUDE.md generator — auto-generates project context from knowledge graph + preferences."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


async def generate_claude_md(orchestrator: Any, output_path: str = "CLAUDE.md") -> str:
    """Generate a CLAUDE.md file from the knowledge graph and user preferences.

    This file is designed to be consumed by Claude Code as project context.
    It includes:
    - User preferences and coding style
    - Known entities and relationships
    - Frequently used tools and commands
    - Project conventions learned over time
    """
    sections: list[str] = []

    sections.append("# CLAUDE.md — Auto-generated by Yoda\n")
    sections.append(
        "> This file is auto-generated from Yoda's knowledge graph and learned preferences.\n"
        "> It provides context for Claude Code about the user and their project.\n"
    )

    # User preferences from memory
    preferences = await _get_preferences(orchestrator)
    if preferences:
        sections.append("## User Preferences\n")
        for pref in preferences:
            sections.append(f"- {pref}")
        sections.append("")

    # Knowledge graph entities
    entities = await _get_key_entities(orchestrator)
    if entities:
        sections.append("## Key Context\n")
        for entity in entities:
            sections.append(f"- **{entity['name']}** ({entity['type']}): {entity.get('desc', '')}")
        sections.append("")

    # Coding conventions
    conventions = await _get_conventions(orchestrator)
    if conventions:
        sections.append("## Coding Conventions\n")
        for conv in conventions:
            sections.append(f"- {conv}")
        sections.append("")

    # Frequently used tools
    tools = await _get_tool_preferences(orchestrator)
    if tools:
        sections.append("## Preferred Tools & Commands\n")
        for tool in tools:
            sections.append(f"- {tool}")
        sections.append("")

    # If no data, provide a template
    if len(sections) <= 2:
        sections.append("## Getting Started\n")
        sections.append(
            "No preferences or knowledge stored yet. "
            "Chat with Yoda to build up context over time.\n"
        )
        sections.append("Yoda will automatically learn:\n")
        sections.append("- Your coding style and preferences")
        sections.append("- Important people, projects, and concepts")
        sections.append("- Frequently used tools and commands")
        sections.append("- Project conventions and patterns")
        sections.append("")

    content = "\n".join(sections)

    # Write to file
    path = Path(output_path)
    path.write_text(content)
    logger.info("Generated CLAUDE.md at %s", path.resolve())

    return content


async def _get_preferences(orchestrator: Any) -> list[str]:
    """Extract user preferences from memory."""
    plugin = orchestrator.get_plugin("memory")
    if not plugin:
        return []

    try:
        result = await plugin.execute(
            "memory_search",
            {"query": "user preferences coding style", "collection": "preferences", "top_k": 10},
        )
        if result and result != "No relevant memories found.":
            # Parse the memory search results
            items = []
            for block in result.split("---"):
                block = block.strip()
                if block:
                    # Extract content after the metadata line
                    lines = block.split("\n", 1)
                    if len(lines) > 1:
                        items.append(lines[1].strip())
                    elif lines:
                        items.append(lines[0].strip())
            return items[:10]
    except Exception:
        logger.debug("Failed to get preferences", exc_info=True)
    return []


async def _get_key_entities(orchestrator: Any) -> list[dict[str, str]]:
    """Extract key entities from knowledge graph."""
    plugin = orchestrator.get_plugin("knowledge_graph")
    if not plugin:
        return []

    try:
        stats_result = await plugin.execute("kg_stats", {})
        # If graph has entities, get details
        if "Entities: 0" not in str(stats_result):
            result = await plugin.execute(
                "kg_query", {"question": "What are the most important entities?"}
            )
            if result:
                # Parse entities from query result
                entities = []
                for line in str(result).split("\n"):
                    line = line.strip()
                    if line and not line.startswith("Entity") and not line.startswith("No "):
                        entities.append({"name": line, "type": "concept", "desc": ""})
                return entities[:15]
    except Exception:
        logger.debug("Failed to get entities", exc_info=True)
    return []


async def _get_conventions(orchestrator: Any) -> list[str]:
    """Extract coding conventions from memory."""
    plugin = orchestrator.get_plugin("memory")
    if not plugin:
        return []

    try:
        result = await plugin.execute(
            "memory_search",
            {"query": "coding conventions project rules style guide", "collection": "procedural", "top_k": 5},
        )
        if result and result != "No relevant memories found.":
            items = []
            for block in result.split("---"):
                block = block.strip()
                if block:
                    lines = block.split("\n", 1)
                    content = lines[1].strip() if len(lines) > 1 else lines[0].strip()
                    items.append(content)
            return items[:10]
    except Exception:
        logger.debug("Failed to get conventions", exc_info=True)
    return []


async def _get_tool_preferences(orchestrator: Any) -> list[str]:
    """Extract preferred tools from memory and usage patterns."""
    plugin = orchestrator.get_plugin("memory")
    if not plugin:
        return []

    try:
        result = await plugin.execute(
            "memory_search",
            {"query": "preferred tools commands workflow", "collection": "procedural", "top_k": 5},
        )
        if result and result != "No relevant memories found.":
            items = []
            for block in result.split("---"):
                block = block.strip()
                if block:
                    lines = block.split("\n", 1)
                    content = lines[1].strip() if len(lines) > 1 else lines[0].strip()
                    items.append(content)
            return items[:10]
    except Exception:
        logger.debug("Failed to get tool preferences", exc_info=True)
    return []
